version: "3.9"

services:
    db:
        image: mysql:latest
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ../mysql:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
