version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: your_database_name
            MYSQL_ROOT_PASSWORD: your_root_password

    redis:
        image: redis:latest

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app
